In [1]:
import torch
import torch.nn as nn


In [14]:
torch.randn(4)

tensor([ 0.8984,  1.9599, -0.6797,  1.1936])

In [38]:
x=torch.randn(2,1,3,3,1)
print(x.shape)
print(x)
x=x.squeeze()
print(x)

torch.Size([2, 1, 3, 3, 1])
tensor([[[[[ 1.5063],
           [-0.9827],
           [ 0.7493]],

          [[-0.2031],
           [ 1.0390],
           [ 1.3257]],

          [[ 0.8072],
           [ 0.2391],
           [-0.2504]]]],



        [[[[ 0.8521],
           [-0.4851],
           [ 1.2427]],

          [[-0.3762],
           [ 0.8644],
           [ 0.8439]],

          [[-1.2952],
           [ 0.3016],
           [ 0.1870]]]]])
tensor([[[ 1.5063, -0.9827,  0.7493],
         [-0.2031,  1.0390,  1.3257],
         [ 0.8072,  0.2391, -0.2504]],

        [[ 0.8521, -0.4851,  1.2427],
         [-0.3762,  0.8644,  0.8439],
         [-1.2952,  0.3016,  0.1870]]])


In [36]:
print(x.shape)

torch.Size([2, 3, 3])
